version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  # gitea
  gitea:
    build:
      context: ./gitea
      args:
        - GITEA_VERSION=${GITEA_VERSION}
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://${GITEA_HOST}:${GITEA_WEB_PORT}
      - DOMAIN=${GITEA_HOST}
      - SSH_PORT=${GITEA_SSH_PORT}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PWD}
    volumes:
      - ${VOLUMES_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_WEB_PORT}:3000
      - ${GITEA_SSH_PORT}:22
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PWD}
      - POSTGRES_DB=${GITEA_DB_NAME}
    volumes:
      - ${VOLUMES_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - backend

  # jenkins
  jenkins:
    build:
      context: ./jenkins
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    restart: always
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'
    privileged: true
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_JNLP_PORT}:50000"
    volumes:
      - ${VOLUMES_PATH}/jenkins/jenkins_home:/var/jenkins_home
      - ${JENKINS_DOCKER_SOCK}:/var/run/docker.sock
      - ${JENKINS_DOCKER}:/usr/bin/docker
      - ${KUBECTL_BIN_PATH}:/usr/local/bin/kubectl
      - ${K8S_KUBE_CONFIG}:/root/.kube
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      # 非Linux环境运行，需要注释
      - ${LIBLTDL_SO}:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    networks:
      - backend
